Repository Aatu/FieryVoid, pull requests merged in 2020-10, with the labels that each got.

#847 Corrections to Circasian Dual and Heavy Rockets
  source/autoload.php
Labels: bug

#852 Douglas changes
  source/public/img/ships/DescariCroscotu.png
  source/public/img/ships/DescariCruscava.png
  source/public/img/ships/DescariScorran.png
  source/server/model/ships/abbai_old/kastona.php
  source/server/model/ships/descari/Croscotu.php
  source/server/model/ships/descari/CroscotuEarly.php
  source/server/model/ships/descari/CroscotuRefit.php
  source/server/model/ships/descari/Cruscava.php
Labels: enhancement

#858 Descari img and Scorota thruster fix
  source/public/img/ships/DescariCarrana.png
  source/public/img/ships/DescariRulnar.png
  source/public/img/ships/DescariRulnata.png
  source/public/img/ships/DescariScorota.png
  source/server/model/ships/descari/Scorota.php
Labels: bug, enhancement

#862 minor fixes
  source/public/img/ships/DescariCarrana.png
  source/public/img/ships/DescariRulnar.png
  source/public/img/ships/DescariRulnata.png
  source/public/img/ships/DescariScorota.png
  source/server/model/ships/descari/Scorota.php
Labels: bug, enhancement
