Repository Aatu/FieryVoid, pull requests merged in 2020-05, with the labels that each got.

#721 new graphics (Douglas)
  source/public/img/ships/AbbaiSellac.png
  source/public/img/ships/Brahassa.png
  source/public/img/ships/ChlonasAnVothi.png
  source/public/img/ships/ChlonasXerEnthain.png
  source/public/img/ships/Cidikar.png
  source/public/img/ships/DenethDeliverer.png
  source/public/img/ships/DenethLiberator.png
  source/public/img/ships/DenethProtector.png
  source/public/img/ships/DenethProvider.png
  source/public/img/ships/DenethVindicator.png
  source/public/img/ships/DenethWatcherScout.png
  source/public/img/ships/DenethWatchtower.png
  source/public/img/ships/Hassa.png
  source/public/img/ships/Talasi.png
  source/public/img/ships/Tashkat.png
  source/public/img/ships/TorataAtlac.png
  source/public/img/ships/TorataClovant.png
  source/public/img/ships/TorataColotnar.png
  source/public/img/ships/TorataDartoc.png
  source/public/img/ships/TorataGolthar.png
  source/public/img/ships/TorataHeltaka.png
  source/public/img/ships/TorataHeltakaNOPODS.png
  source/public/img/ships/TorataLatrac.png
  source/public/img/ships/TorataToglat.png
  source/public/img/ships/TorataTralka.png
  source/public/img/ships/TorataTralka_Large.png
  source/public/img/ships/TorataTuka.png
  source/public/img/ships/TorataTuka_Large.png
  source/public/img/ships/TorataTumal.png
  source/server/model/ships/brakiri/cidikar.php
  source/server/model/ships/deneth/providerFreighter.php
  source/server/model/ships/deneth/watcher.php
  source/server/model/ships/torata/torataDartocCA.php
  source/server/model/ships/torata/torataLatracCE.php
Labels: feature

#723 grapics fixes
  source/public/img/ships/DenethLiberator.png
  source/public/img/ships/DenethProtector.png
  source/server/model/ships/deneth/providerFreighter.php
Labels: bug, enhancement

#741 Hearpa 7Orion
  source/autoload.php
  source/public/img/ships/BrakiriCidikar.png
  source/public/img/ships/DenethDeliverer.png
  source/public/img/ships/DenethVindicator.png
  source/server/model/ships/EA/OrionDelta.php
  source/server/model/ships/ZCustomChLonas/wlcChlonasHeArpa.php
  source/server/model/ships/brakiri/cidikar.php
Labels: feature

#748 Special fighter hangar requirements
  source/public/client/gamelobby.js
Labels: enhancement
